### ISSUE TITLE
tried one song, not accurate :(

### ISSUE THREAD

**Issue by ice6** [alexandrglm/Chordyzer#1]

**Comment by alexandrglm** [comment]
@ice6 If you think your attitude when opening an issue was not summing/adding more than a topic message with no content/context please, notice me, and close the issue.

Thanks.

**Comment by ice6** [comment]
@alexandrglm Hi, thanks for you kindly reply, I will try the initial release(https://github.com/alexandrglm/Chordyzer/releases/tag/Chordy) for evaluating purpose.
